using System;
using Microsoft.Xna.Framework;
using Nez;
using GorelordsBrawler.Constants;

namespace GorelordsBrawler.Components.Hazards
{
	/// <summary>
	/// A static refuge tier that the acid EATS hole-by-hole. Spawned by
	/// ArenaScene from the TMX "tiers" object layer (tiers can't be static
	/// collision tiles — tiles can't erode). This is a thin host: it owns the
	/// tier's identity (rank) and forwards the "fully eaten" event; the actual
	/// swiss-cheese erosion + per-cell collision lives in
	/// <see cref="ErodibleSurface"/>.
	///
	/// Per-rank death counts drive the ROCKFALL's drop-column unlocks
	/// (ArenaScene subscribes to <see cref="OnDissolved"/>): a ghost column
	/// only opens once its tier pair is gone.
	/// </summary>
	public class DissolvingPlatform : Component
	{
		/// <summary>Tier rank from the TMX ("low" / "mid" / "top").</summary>
		public readonly string Rank;

		/// <summary>Fired once when the tier is fully eaten (entity about to be destroyed).</summary>
		public Action OnDissolved;

		private readonly AcidSurface _acid;
		private readonly float _width;
		private readonly float _height;
		private ErodibleSurface _erodible;

		// Greybox tier color (matches the old static-tile look until Phase E).
		private static readonly Color _tierColor = new Color(110, 110, 115);

		public DissolvingPlatform(AcidSurface acid, float width, float height, string rank)
		{
			_acid   = acid;
			_width  = width;
			_height = height;
			Rank    = rank ?? "";
		}

		public override void OnAddedToEntity()
		{
			// Phase E: grimy bolted-steel slab texture (generated by
			// tools/gen_arena_tileset.py). Erosion carves holes through the
			// stable image — the renderer maps it onto the slab proportionally.
			var texture = Entity.Scene.Content.LoadTexture(
				Nez.Content.Sprites.Hazards.Tier_metal);
			_erodible = Entity.AddComponent(new ErodibleSurface(
				_acid, _width, _height, _tierColor,
				AcidConfig.TierErosionPassesPerSec, texture));
			_erodible.OnFullyEroded = () => OnDissolved?.Invoke();
		}
	}
}
